### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kog** [kog/SpikeCore#1]
In no particular order...

- [ ] README markdown
- [ ] Wire in Autofac
- [ ] Get message workflow going 
- [ ] Wire up preliminary modules
- [ ] Whatever cleanup we need for ASP.NET stuff
- [ ] Get auth going

**Comment by kog** [comment]
I figure once we get through this list, we can call the bot a 1.0.

**Comment by kog** [comment]
#44 adds basic user management to the bot, which will make it easier to move from shared users to distinct users for folks that want to use the web UI. Still need to figure out credentials (standard username/password? tokens?), but it's a step towards getting it working properly.
